dev/com.ibm.ws.st.jee.core/src/com/ibm/ws/st/jee/core/internal/JEEServerExtension.java
=> Fix default context root resolution for web modules within EARs

dev/com.ibm.ws.st.common.core.ext/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.common.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.common.ui.ext/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.common.ui/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.docker.base/feature.xml, dev/com.ibm.ws.st.docker.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.docker.ui/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.jee.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.jee.ui/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.ui/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.was.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.was.tools.common.core/feature.xml, dev/com.ibm.ws.st.was.tools.common.ui/feature.xml
=> Issue #30: Update plugin and feature versions

dev/com.ibm.xwt.dde.feature/feature.xml, dev/com.ibm.xwt.dde/META-INF/MANIFEST.MF
=> Issue #33: update DDE feature and plugin versions

dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/xml/internal/ProjectMapXML.java, dev/com.ibm.ws.st.liberty.buildplugin.integration/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.liberty.buildplugin.integration/plugin.properties, dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/servertype/internal/AbstractLibertyBuildPluginJEEPublisher.java, dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/servertype/internal/AbstractLibertyBuildPluginServerBehaviour.java, dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/ui/internal/AbstractCustomServerConfig.java, dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/ui/rtexplorer/internal/AbstractLibertyBuildPluginRuntimeLabelProvider.java, dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/xml/internal/AbstractProjectMapXML.java, dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/xml/internal/DOMBasedLibertyBuildPluginConfigurationBuilder.java, dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/xml/internal/LibertyBuildPluginXMLConfigurationReader.java
There are still a few references to maven in the common plugin that need to be cleaned up.
=> Cleanup remaining maven references

dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/servertype/internal/LibertyMavenJEEPublisher.java, dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/servertype/internal/AbstractLibertyBuildPluginJEEPublisher.java
=> [48] Maven-specific post/pre-publish code still in common plugin

dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/internal/LibertyGradle.java, dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/internal/LibertyGradleConstants.java, dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/servertype/internal/LibertyGradleJEEPublisher.java
Fixes #52 
Implement code to run Gradle tasks.
=> Issue #52: Implement code to run Gradle tasks

dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/internal/LibertyMavenConstants.java, dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/ui/actions/internal/RefreshAction.java, dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/ui/rtexplorer/internal/MavenRuntimeContentProvider.java, dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/ui/actions/internal/AbstractRefreshAction.java, dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/ui/rtexplorer/internal/AbstractBuildPluginRuntimeActionProvider.java, dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/ui/rtexplorer/internal/AbstractLibertyBuildPluginRuntimeContentProvider.java, dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/ui/rtexplorer/internal/LibertyBuildPluginProjectNode.java, dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/internal/LibertyGradleConstants.java, dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/ui/actions/internal/RefreshAction.java, dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/ui/rtexplorer/internal/GradleRuntimeContentProvider.java
=> [54] Duplicate context menu actions on build plugin runtime obj.

dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/BluemixLinkTest.java, dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/ToolsTestBase.java
BluemixLinkTest - The text in the web page has changed so update the test case
Docker external folder tests (JEEPublishWarNoDDExt, JEEPublishEarDDExt) - the temp directory used to copy the projects into should be cleaned up
=> Issue #68: Fix some test case problems

dev/com.ibm.ws.st.liberty.gradle/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.liberty.gradle/build.properties, dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/internal/Activator.java, dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/internal/Messages.java, dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/internal/Messages.properties, dev/com.ibm.ws.st.liberty.tools.base/feature.xml
Fixes #84 
Install support for Liberty Gradle integration.
=> Issue #84: install support for Liberty Gradle integration

dev/com.ibm.ws.st.core/template/bootstrap.properties, dev/com.ibm.ws.st.core/template/jvm.options, dev/com.ibm.ws.st.core/template/server.env, dev/com.ibm.ws.st.core_tests/resources/abbot/OpenLogFilesTest/bootstrap_backup.properties, dev/com.ibm.ws.st.core_tests/resources/jee/JEE7/Web7/.settings/org.eclipse.wst.common.project.facet.core.xml, dev/com.ibm.ws.st.core_tests/resources/jee/JEE7/Web7EAR/.settings/org.eclipse.wst.common.project.facet.core.xml, dev/com.ibm.ws.st.core_tests/resources/validation/serverEnv/files/config/server.env, dev/com.ibm.ws.st.core_tests/resources/validation/serverEnv/files/etc/server.env, dev/com.ibm.ws.st.docker.ui/src/com/ibm/ws/st/docker/ui/internal/wizard/LibertyDockerComposite.java, dev/com.ibm.ws.st.was.core/plugin.properties
Fixes #46 
Update the server label to Liberty Server and the runtime label to Liberty Runtime.
=> Issue #46: update server and runtime labels

dev/com.ibm.ws.st.liberty.tools.base/feature.xml
Fixes #96 
Temporarily disable Gradle integration support.
=> Issue #96 - temporarily disable Gradle integration support

dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/internal/AbstractCustomServerVariablesHandler.java
Fixes #102 
Use the existing Bootstrap and ServerEnv classes for reading in the files and gathering the variables.
=> Issue #102: Fix processing of server.env for Maven integration

dev/com.ibm.ws.st.liberty.tools.base/feature.xml
Fixes #105 
Re-enable Gradle integration
=> Issue #105: Re-enable Gradle integration

dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/ui/internal/AbstractCustomServerConfig.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/utility/PathUtil.java
=> [107] Derived Server Config Content Not Showing

dev/com.ibm.ws.st.core/featureList.xml, dev/com.ibm.ws.st.core/server.xsd, dev/com.ibm.ws.st.ui/xml/Customization.properties
Fixes #111 
Update
- default server configuration schema
- default runtime feature list
- server configuration editor customization files - there were no changes but removed the duplicate copyright in the Customization.properties file
=> Issue #111 - update default schema, feature list and customization

dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/ConsoleMonitorThread.java, dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/util/WLPCommonUtil.java
Fixes #109 
- support JSON console log format
- add code to allow running tests with JSON console log format enabled
=> Issue #109: Support JSON console log format

dev/com.ibm.ws.st.liberty.gradle/META-INF/MANIFEST.MF
Fixes #122 
Export liberty gradle packages as internal for test use.
=> 122 export liberty gradle packages for test

dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/service/setup/LibertySetup.java, dev/com.ibm.ws.st.docker.core/src/com/ibm/ws/st/docker/core/internal/launch/LibertyDockerLaunchConfiguration.java, dev/com.ibm.ws.st.docker.core/src/com/ibm/ws/st/docker/core/internal/launch/LibertyDockerRunUtility.java, dev/com.ibm.ws.st.docker.core/src/com/ibm/ws/st/docker/core/internal/launch/LibertyDockerServerBehaviour.java, dev/com.ibm.ws.st.docker.ui/src/com/ibm/ws/st/docker/ui/internal/wizard/LibertyDockerComposite.java, dev/com.ibm.ws.st.docker.ui/src/com/ibm/ws/st/docker/ui/internal/wizard/LibertyDockerUtil.java
Fixes #133 
Add a check for the Open Liberty install path (/opt/ol/wlp) in Docker
containers.
=> Issue #133: check for Open Liberty install path in Docker container

dev/com.ibm.ws.st.core/featureList.xml, dev/com.ibm.ws.st.core/server.xsd
Fixes #138 
Update the default schema and feature list to 17.0.0.4 version.
=> Issue #138: update default schema and feature list to 17.0.0.4 version

dev/com.ibm.ws.st.core_tests/resources/abbot/noisyServlet/noisyservlet/src/NoisyServlet.java
Fixes #126 
NoisyServlet.java is missing from the test resources.
=> Issue #126: NoisyServlet.java missing from test resources

dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/servertype/internal/LibertyMavenJEEPublisher.java, dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/servertype/internal/LibertyGradleJEEPublisher.java
Fixes #153 
Multi-module projects don't have to be an ear so check for aggregatorParentId and aggregatorParentBasedir instead.
=> Issue #153: fix publishing for multi-module Maven and Gradle projects

dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/jmx/JMXConnection.java
Fixes #3 
Print out the added, changed and removed files.
=> Issue #3: improve tracing for JMXConnection notifyFileChanges

dev/com.ibm.ws.st.core_tests/resources/FeatureTesting/MixedFeatureTest/JSONB10/.settings/org.eclipse.wst.common.project.facet.core.xml, dev/com.ibm.ws.st.core_tests/resources/FeatureTesting/MixedFeatureTest/JSONP11/.settings/org.eclipse.wst.common.project.facet.core.xml, dev/com.ibm.ws.st.core_tests/resources/FeatureTesting/MixedFeatureTest/Web8EAR/.settings/org.eclipse.wst.common.component
Fixed JSONB and JSONP projects to 4.0 Dynamic Web Module, fixed EAR8 Deployment Assembly Path
=> Issue #166: Fix MixedFeatureTest

dev/com.ibm.ws.st.core/featureList.xml, dev/com.ibm.ws.st.core/server.xsd
Fixes #172 
Update runtime fallback metadata (there were no changes to the editor customization files).
=> Issue #172: update runtime fallback metadata

dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/APIVisibility.java, dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/Constants.java, dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/ProjectPrefs.java, dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/WebSphereRuntimeClasspathProvider.java, dev/com.ibm.ws.st.jee.ui/src/com/ibm/ws/st/jee/ui/internal/Messages.java, dev/com.ibm.ws.st.jee.ui/src/com/ibm/ws/st/jee/ui/internal/Messages.properties, dev/com.ibm.ws.st.jee.ui/src/com/ibm/ws/st/jee/ui/internal/SharedLibPropertiesPage.java, dev/com.ibm.ws.st.jee.ui/src/com/ibm/ws/st/jee/ui/internal/UtilityProjectSharedLibPropertiesPage.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/ClasspathPropertyPage.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/Messages.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/Messages.properties
=> Issue #176: Support stable API type visibility

dev/com.ibm.ws.st.common.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.jee.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.liberty.buildplugin.integration/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.liberty.gradle/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.liberty.tools.base/feature.xml, dev/com.ibm.ws.st.ui/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.was.tools.common.core/feature.xml
=> Issue #178: update plugin and feature versions

dev/com.ibm.ws.st.core/featureList.xml, dev/com.ibm.ws.st.core/server.xsd
Fixes #182 
Update the fallback schema and feature list.
=> Issue #182: update fallback schema and feature list

dev/ant_build/build-olt.xml, dev/build.gradle, dev/com.ibm.ws.st.liberty.tools/feature.xml
=> Issue #184: 18002 version update

dev/com.ibm.xwt.dde/src/com/ibm/xwt/dde/internal/viewers/ErrorMessageSummaryPopupDialog.java
=> Issue #187: Update deprecated PopupDialog constructor call

dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/Constants.java, dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/WebSphereRuntime.java, dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/repository/IRuntimeInfo.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/Messages.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/Messages.properties, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/actions/AddOnRuntimeAction.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/actions/ConfigSnippetAction.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/config/FeatureUI.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/download/AbstractProduct.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/download/AddonsWizardFragment.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/download/DownloadHelper.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/download/LocalProduct.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/download/ProductHelper.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/download/ProductMatcher.java
Add support for multiple properties files in the runtime lib/versions
folder.
=> Issue #185: support multiple version properties files

dev/ant_build/build-olt.xml, dev/ant_build/olt_imports.xml, dev/ant_build/olt_test_imports.xml, dev/ant_build/public_imports/updatesite_imports.xml, dev/build.gradle
=> Issue #195: Sign open liberty tools jar

dev/gradle.properties
Update target platform and SDK to Oxygen.3
=> Issue #194: Update to  Oxygen.3

dev/com.ibm.ws.st.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.core_tests/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.liberty.buildplugin.integration/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.ui/META-INF/MANIFEST.MF
=> Issue #200: Update versions based on version scan report

dev/com.ibm.ws.st.core/featureList.xml, dev/com.ibm.ws.st.core/server.xsd, dev/com.ibm.ws.st.ui/xml/CustomizationFile.xml
Fixes #205 
Update schema, feature list and customization files.
=> Issue #205: Update schema, feature list and customization files.

dev/com.ibm.ws.st.core/featureList.xml, dev/com.ibm.ws.st.core/server.xsd
Fixes #209 
Update the schema and feature list based on the latest runtime.
There were no changes to the customization files based on the latest schema.
Note that these are all generated files.
=> Issue #209: update schema and feature list

dev/ant_build/public_imports/internal_imports/universal_properties.xml
Update the remote gsa server property to rtpgsa since ausgsa no longer works.
=> ausgsa is no longer in service so switch to rtpgsa for builds

dev/ant_build/build-olt.xml, dev/com.ibm.ws.st.liberty.tools/feature.xml
=> Issue #215 : 18.0.0.3 Version update

dev/com.ibm.ws.st.core/featureList.xml, dev/com.ibm.ws.st.core/server.xsd
There were no changes to the editor customization files so just updating the default schema and feature list.
=> Issue #220: Update feature list and schema based on latest runtime

dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/config/ConfigUtils.java
Fixes #231 
For an external user directory the project is always null.  Add missing check for null project.
=> Issue #231: For external user dir project is null so need to check

dev/com.ibm.ws.st.core/featureList.xml, dev/com.ibm.ws.st.core/server.xsd
For tracking purpose, issue here: https://github.com/OpenLiberty/open-liberty-tools/issues/233
Update feature list, schema based on latest runtime, the customization file doesn't change.
=> Update feature list, schema based on latest runtime

dev/ant_build/build-olt.xml, dev/com.ibm.ws.st.liberty.tools/feature.xml
=> Issue #245: 18.0.0.4 Version update

dev/com.ibm.ws.st.core/featureList.xml, dev/com.ibm.ws.st.core/server.xsd, dev/com.ibm.ws.st.ui/xml/CustomizationFile.xml, dev/gradle.properties
=> 248 update metadata and customization

dev/com.ibm.ws.st.common.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.core_tests/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.docker.base/feature.xml, dev/com.ibm.ws.st.liberty.tools.base/feature.xml, dev/com.ibm.ws.st.liberty.tools.test/feature.xml, dev/com.ibm.ws.st.was.tools.common.core/feature.xml, dev/gradle.properties
=> 250 update versions

dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/util/ServerTestUtil.java, dev/gradle.properties
Fixes #253 
Remove the dependency on javax.xml.bind.DatatypeConverter.
=> 253 remove dependeny on DatatypeConverter

dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/launch/ExternalProcess.java, dev/gradle.properties
Fixes #257 
Respect the stop server on shutdown setting for remote servers.
=> 257 Respect the stop server on shutdown setting for remote servers

dev/com.ibm.ws.st.common.core.ext/src/com/ibm/ws/st/common/core/ext/internal/util/BaseDockerContainer.java
Fixes #258 
Fix up file permissions on configuration files copied to the Liberty docker container.
=> Issue #258: Fix file permissions on configuration files copied to docker container

dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/manager/internal/MavenProjectInspector.java, dev/gradle.properties
Close the pom.xml file after reading it in.
=> Issue #240: Close the pom.xml file after reading it in

dev/com.ibm.ws.st.common.core.ext/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.common.ui/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.ui/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.was.tools.common.ui/feature.xml, dev/gradle.properties
=> 266 update versions

dev/com.ibm.etools.maven.liberty.integration/META-INF/MANIFEST.MF, dev/gradle.properties
=> 268 update maven plugin version

dev/ant_build/build-olt.xml, dev/com.ibm.ws.st.liberty.tools/feature.xml
=> Version update to 19.0.0.3

dev/com.ibm.ws.st.core_tests/resources/sampleTesting/JAXWSWebSample/server/server.xml
Fixes #278 
Hard coded both the jaxb and jaxws feature versions to be on the safe side.  Other test cases cover feature detection.
=> Issue #278: fix JAXWSWebSample test case to not have feature conflicts

dev/com.ibm.ws.st.jee.core/plugin.xml, dev/gradle.properties
There are no facets for jdbc so just add jdbc-4.3 to the runtime composition.
=> Issue #281: add support for jdbc-4.3

dev/com.ibm.ws.st.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.core_tests/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.docker.base/feature.xml, dev/com.ibm.ws.st.jee.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.liberty.tools.base/feature.xml, dev/com.ibm.ws.st.ui/META-INF/MANIFEST.MF, dev/gradle.properties
Update the plugin and feature versions based on the version scan.
=> Issue #289: Update plugin and feature versions for next release

dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/Constants.java, dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/Messages.java, dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/Messages.properties, dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/config/ConfigUtils.java, dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/config/validation/AbstractConfigurationValidator.java, dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/AllSmokeTests.java, dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/validation/AllValidationTests.java, dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/validation/VariableDefaultValueTest.java, dev/com.ibm.ws.st.core_tests/resources/validation/variableDefaultValue1/include.xml, dev/com.ibm.ws.st.core_tests/resources/validation/variableDefaultValue1/server.xml, dev/com.ibm.ws.st.core_tests/resources/validation/variableDefaultValue2/server.xml, dev/com.ibm.ws.st.core_tests/resources/validation/variableDefaultValue3/bootstrap.properties, dev/com.ibm.ws.st.core_tests/resources/validation/variableDefaultValue3/include.xml, dev/com.ibm.ws.st.core_tests/resources/validation/variableDefaultValue3/server.xml, dev/com.ibm.ws.st.core_tests/resources/validation/variableDefaultValue4/include.xml, dev/com.ibm.ws.st.core_tests/resources/validation/variableDefaultValue4/server.xml, dev/com.ibm.ws.st.core_tests/resources/validation/variableDefaultValueMsgs/server.xml
Add support for variable default values.
=> Issue #280: Add support for variable default values

dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/UtilitiesTestCase.java
Issue is here: https://github.com/OpenLiberty/open-liberty-tools/issues/297
=> Issue #297: Update key file name for test case testSSLCertificate

dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/jee/AllJEETests.java, dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/jee/AllJEETests_LooseCfg.java, dev/gradle.properties
=> 306 Add JEEMultiLocationPublish tests to the JEE test lists

dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/DockerUtilitiesTest.java, dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/docker/LibertyDockerTestExt.java
Issue in OLT: https://github.com/OpenLiberty/open-liberty-tools/issues/309
=> Fix test case testSSLCertificate

dev/build.gradle
=> Issue #312: Clean ivy cache directory for build

dev/com.ibm.ws.st.core/featureList.xml, dev/com.ibm.ws.st.core/server.xsd
There were no changes to the editor customization files.
=> Issue #318: Update fallback metadata and customization files

dev/com.ibm.ws.st.common.core.ext/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.common.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.common.ui.ext/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.common.ui/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.core_tests/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.docker.base/feature.xml, dev/com.ibm.ws.st.docker.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.docker.ui/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.jee.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.jee.ui/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.liberty.tools.base/feature.xml, dev/com.ibm.ws.st.liberty.tools.test/feature.xml, dev/com.ibm.ws.st.tests.common.util/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.ui/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.was.tools.common.core/feature.xml, dev/com.ibm.ws.st.was.tools.common.ui/feature.xml
=> Update plugin and feature versions for next release

dev/ant_build/build-olt.xml, dev/com.ibm.ws.st.liberty.tools/feature.xml
=> Issue #329: Version update to 19.0.0.9

dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/DockerUtilitiesTest.java
This PR is to fix the issue of DockerUtilitiesTest failing on testSSLCertificate: https://github.com/OpenLiberty/open-liberty-tools/issues/309
=> Fix test certificate

dev/com.ibm.ws.st.core/featureList.xml, dev/com.ibm.ws.st.core/server.xsd
Fixes #337 
Updated the schema and feature list.  There were no changes to the customization files.
=> Issue #337: Update the schema and feature list based on latest runtime

dev/com.ibm.ws.st.core/featureList.xml, dev/com.ibm.ws.st.core/server.xsd, dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/ConsoleMonitorThread.java, dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/WebSphereRuntime.java
- Updated schema and feature list
- No changes to the customization files
- Updated copyrights for files changed in #351
=> Issue #352: Update feature list, schema and customization file based latest runtime

dev/com.ibm.ws.st.core/META-INF/MANIFEST.MF, dev/com.ibm.ws.st.docker.base/feature.xml, dev/com.ibm.ws.st.liberty.tools.base/feature.xml
=> Issue #354: Update plugin and feature versions for next release

dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/AbstractMonitorThread.java
Add a system property for overriding the server status polling delay.
=> Issue #356: allow user to override server status polling delay

dev/ant_build/build-olt.xml, dev/com.ibm.ws.st.liberty.tools/feature.xml
=> fixes #363 20.0.0.3 Version update

README.md
Reverts OpenLiberty/open-liberty-tools#373
=> Revert "The README should probably link to some tools docs"

README.md, dev/build.gradle
Merge https://github.com/OpenLiberty/open-liberty-tools/pull/373 into **integration** branch
=> The README should probably link to some tools docs

dev/ant_build/build-olt.xml, dev/com.ibm.ws.st.liberty.tools/feature.xml
Fixes Issue  #386  - 20.0.0.6 Version update
=> Issue  #386: Version update to 20.0.0.6

dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/validation/MiscellaneousValidationTest.java, dev/com.ibm.ws.st.core_tests/resources/validation/unavailableElement/server.xml
Fix the unavailable element test case to use different elements now that the jdbc elements are enabled by default in an auto feature.
=> Issue #392: Fix unavailable element test case

dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/ToolsTestBase.java, dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/jee/featureDetection/BaseFeatureTest.java, dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/jee/featureDetection/MixedFeatureTest.java, dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/samples/CDISample.java, dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/samples/NonPersistentTimerSample.java, dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/util/FeatureUtil.java, dev/com.ibm.ws.st.core_tests/resources/OutOfSyncTesting/outOfSyncServer/server.xml
Some test cases need updating since new Jakarta features are causing feature conflicts.
=> Issue #394: Fix test case failures caused by new Jakarta features

dev/ant_build/build-olt.xml, dev/com.ibm.ws.st.liberty.tools/feature.xml
Signed-off-by: Alif Munim <alif.munim@ryerson.ca>
=> Update liberty version to 20.0.0.9

README.md
=> Updated twitter reference to OpenLibertyIO

dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/module/ModuleHelper.java
Eclipse made change for default path for webapps to src/main/webapp rather than webcontent
=> Fix path for html file in test

CONTRIBUTING.md, README.md
Signed-off-by: Matthew Colegate <COLEGATE@uk.ibm.com>
=> Rename prohibited terms

dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/ConsoleLineTrackerHelper.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/ConsoleLineTracker.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/Messages.properties, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/download/AddonUtil.java, dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/wizard/WebSphereDefaultServerComposite.java
Signed-off-by: Matthew Colegate <COLEGATE@uk.ibm.com>
This PR removes some prohibited terms from the source code.
=> Prohibited terms removal
