OpenLiberty/open-liberty-tools

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/WebSphereRuntime.java
- dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/RuntimeDropAdapter.java
- dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/download/DownloadHelper.java
- dev/com.ibm.ws.st.ui/src/com/ibm/ws/st/ui/internal/download/LocalProduct.java
Fixes #1 
Check for both WebSphereApplicationServer.properties and openliberty.properties file in wlp/lib/versions so that all liberty runtimes can be supported.
> Issue #1: add check for openliberty.properties file

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/WebSphereServerBehaviour.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/OutOfSyncTest.java
Fixes #6
If more than one server extension exists then make sure the code keeps checking the extensions for an out of sync situation.
Also fix the OutOfSyncTest case so that the imported projects compile.
> Issue #6: keep checking server extensions for out of sync situation

- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/UtilitiesTestCase.java
Fixes #7
After each package install test, the runtime should be removed so that the next package install test does not pass incorrectly.
> Issue #7: The runtime should be deleted after each package install test

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/Messages.java
- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/Messages.properties
- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/WebSphereServerBehaviour.java
Fixes #12
The following message suggests starting the remote server in order to publish but remote start is not supported so remove the message. The server will be in republish state.
"The server needs to be started so that you can publish. Start the server and publish again."
> Issue #12: Remote start not supported so remove related message

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/ServerExtensionWrapper.java
Multiple server extensions can reference the same application types and elements causing the ServerExtensionWrapper to list them more than once. The ServerExtensionWrapper should use sets instead of lists since each type should only be processed once. This also prevents duplicate application modules from being listed under a server.
> Fix duplicate applications issue

- dev/com.ibm.ws.st.liberty.tools.base/feature.xml
Fixes #26
- A requires is missing for the common ui feature
- For the requires the versions have .qualifier on the end which should not be there
> Issue #26: fix com.ibm.ws.st.liberty.tools.base feature

- dev/com.ibm.ws.st.jee.core/src/com/ibm/ws/st/jee/core/internal/JEEServerExtension.java
Fixes #35
The JEEContextRoot_EAR_NoDD_CRinWebXML is failing because of a commit for issue #18. The change will be reverted until the problem can be further investigated.
> Issue #35: revert change causing context root test case to fail

- dev/com.ibm.etools.maven.liberty.integration/plugin.xml
- dev/com.ibm.ws.st.liberty.gradle/plugin.xml
- dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/internal/CustomServerVariablesHandler.java
- dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/internal/LibertyGradleConstants.java
- dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/manager/internal/GradleProjectInspector.java
Fixes #80
Support bootstrap properties variables supplied directly in the build.gradle file as well as in the bootstrap.properties file and env variables in the server.env file.
Also fixed duplicate declarations of the custom server variables extensions (both Gradle and Maven) and cleaned up GradleProjectInspector.getGradleProject.
> Issue #80: support bootstrap properties/file and server.env file

- dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/servertype/internal/LibertyMavenServer.java
- dev/com.ibm.ws.st.common.core.ext/src/com/ibm/ws/st/common/core/ext/internal/servertype/AbstractServerExtension.java
- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/ConfigurationResourceChangeListener.java
- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/WebSphereServer.java
- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/WebSphereUtil.java
- dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/servertype/internal/AbstractLibertyBuildPluginServer.java
- dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/servertype/internal/LibertyGradleServer.java
Fixes #98 
For Maven and Gradle make sure that after a change to the src server
configuration, the target or build server configuration is fixed up
again with the localConnector feature enabled and the application update
trigger set to mbean.
> Issue #98: make sure the application update trigger is set to mbean

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/Activator.java
Someone reported seeing a divide by zero error during the runtime configuration file refresh job. They weren't able to reproduce but it appears the problem is caused by a WebSphereServerInfo not containing any references to config files. It's likely a corner case scenario where the user has a server definition in the workspace for a server that no longer exists in the filesystem so it's probably safe enough to just add a check to make sure the server info has some config files references before proceeding.
> Fix divide by zero in server configuration refresh job

- dev/com.ibm.ws.st.liberty.gradle/META-INF/MANIFEST.MF
Fixes #120
Export the com.ibm.ws.st.liberty.gradle.internal package as internal for test use.
> Issue #120: export Liberty Gradle internal package for test use

- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/Java2SecurityTests_LooseCfg.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/docker/AllDockerTests_LooseCfg.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/jee/AllJEETests_LooseCfg.java
Fixes #142
AllJEETests_LooseCfg - remove the instruction to enable Java security
Java2SecurityTests_LooseCfg - should have a @RunWith(AllTests.class)
instead of @RunWith(Suite.class)
AllDockerTests_LooseCfg - add a comment that when running on Windows or
OS X that the workspace must be in the user home directory or another
directory that is shared with Docker
> Issue #142: minor test fixes

- dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/servertype/internal/AbstractLibertyBuildPluginServer.java
Fixes #148
Currently for a Maven or Gradle server the server shows as follows in the Servers view:
rest [rest] [Stopped]
This is confusing because when the server is started, the console view shows:
The server defaultServer is ready to run a smarter planet.
In the Servers view it should have:
rest [defaultServer] [Stopped]
This would make it consistent with non Maven/Gradle servers as well.
> Issue #148: Fix server name for Maven/Gradle

- dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/internal/LibertyMaven.java
- dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/servertype/internal/LibertyMavenJEEPublisher.java
Fixes #159 
Add -DskipLibertyPackage=true the general code to run a Maven goal and remove it anywhere it is set explicitly.
> Issue #159: Add -DskipLibertyPackage=true to all Maven goals

- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/StandaloneLibertyTestExt.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/TestBaseInterface.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/ToolsTestBase.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/docker/DockerServerTest.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/docker/DockerTestUtil.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/docker/LibertyDockerTestExt.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/jee/JEEPublishEarBase.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/jee/JEEPublishEarRemap.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/jee/JEEPublishWarBase.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/remote/RemoteTestUtil.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/util/ServerTestUtil.java
Fixes #164 
Make docker tests more flexible so they can run in parallel by:
- generating a random container name that is not already used
- selecting a random remote host from a list
> Issue #164: Make docker tests more flexible so they can run in parallel

- dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/manager/internal/AbstractLibertyManager.java
- dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/manager/internal/AbstractLibertyProjectMapping.java
Fixes #169 
When installDir is used to share the runtime, the tools should not try to create separate runtimes for each project but should share the runtime as well.
> Issue #169: Handle Maven/Gradle installDir used to share runtime

- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/ToolsTestBase.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/jee/featureDetection/AlternativeFeatureTest.java
- dev/com.ibm.ws.st.core_tests/resources/FeatureTesting/AlternativeFeatureTest/TestJSFFaces/.settings/org.eclipse.wst.common.project.facet.core.xml
- dev/com.ibm.ws.st.core_tests/resources/FeatureTesting/AlternativeFeatureTest/TestJSFFacet/.settings/org.eclipse.wst.common.project.facet.core.xml
Fixes #198 
Instead of hard coding the version, resolve the jsfContainer feature to the latest version supported by the runtime.  Also fix up the targeted runtime on the projects.
> Issue #198: Resolve jsfContainer feature instead of hard coding version

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/config/ConfigVars.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/validation/VariableValidationTest.java
- dev/com.ibm.ws.st.core_tests/resources/validation/varList/server.xml
Fixes #203
The Open Liberty runtime has added the following variable reference syntax to allow variables to be interpreted as lists:
${list(varName)}
Where 'list' is all lower case (case sensitive).
Example:
\<variable name="valuesVariable" value="value1, value2, value3"/\>
\<someElement values="${list(valuesVariable)}"/\>
The tools need to recognize this syntax so that it treats varName as the variable name instead of list(varName).
Handle in the same place that expressions are handled in ConfigVars.resolve (expressions are: ${\<operand\>\<operator\>\<operand\>}, e.g. ${HTTP_port_base+1}).
> Issue 203: support new list variable syntax

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/generation/ResolverFeatureAdapter.java
A new method (getRequiredOSGiEE) was added to the FeatureResource interface which needs to be implemented.  It can just return null as it is not used in feature resolution.
> Issue #225: Implement new method added to FeatureResource interface

- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/samples/JAXWSEJBSample.java
Fix the JAXWSEJBSample test case so that the sample compiles.  The name of the runtime and JDK that are created needs to be fixed to match what is expected in the test case.
Fixes #224
> Issue #224: fix JAXWSEJBSample so the sample compiles

- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/samples/JAXWSEJBSample.java
Fixes #241
Fix the runtime and JDK name for JAXWSEJBSample test case.
> Issue #241: Fix runtime and JDK name for JAXWSEJBSample test case

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/ServerExtensionWrapper.java
- dev/gradle.properties
Fixes #255
If a fallback publisher is created then init should be called on it otherwise wrapper will be null leading to various NPEs.
> 255 Call init on fallback publisher

- dev/com.ibm.ws.st.common.ui/src/com/ibm/ws/st/common/ui/internal/composite/AbstractRemoteServerStartupComposite.java
- dev/gradle.properties
Fixes #264 
Remove the jdk check for Windows OS logon as it is no longer needed.
> 264 Remove jdk check for Windows OS logon

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/generation/ResolverFeatureAdapter.java
- dev/gradle.properties
Fixes #272
The com.ibm.ws.kernel.feature.provisioning.FeatureResource class was changed so ResolverFeatureAdapter.FeatureResource needs to be updated as well.
Removed: getRequiredOSGiEE()
Added: getRequireJava() (can return null for this since feature resolution is done statically in the tools so there are no Java requirements)
> 272 Respond to changes in the FeatureResource class

- dev/com.ibm.ws.st.core_tests/resources/validation/varDefect94757/server.xml
Fixes #276 
Update the VariableValidationTest based on runtime changes - the keepAlive attribute was removed from the executor element.  Switch to another element and attribute with the same type.
> Issue #276: Update VariableValidationTest based on runtime changes

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/config/ConfigUtils.java
- dev/com.ibm.ws.st.core_tests/bvt/src/com/ibm/ws/st/core/tests/validation/MergeRulesValidationTest.java
- dev/com.ibm.ws.st.core_tests/resources/validation/includeConflictIgnore2/a.xml
- dev/com.ibm.ws.st.core_tests/resources/validation/includeConflictIgnore2/b.xml
- dev/com.ibm.ws.st.core_tests/resources/validation/includeConflictIgnore2/server.xml
- dev/com.ibm.ws.st.core_tests/resources/validation/includeConflictIgnore3/a.xml
- dev/com.ibm.ws.st.core_tests/resources/validation/includeConflictIgnore3/b.xml
- dev/com.ibm.ws.st.core_tests/resources/validation/includeConflictIgnore3/c.xml
- dev/com.ibm.ws.st.core_tests/resources/validation/includeConflictIgnore3/server.xml
- dev/com.ibm.ws.st.core_tests/resources/validation/includeConflictIgnore4/a.xml
- dev/com.ibm.ws.st.core_tests/resources/validation/includeConflictIgnore4/b.xml
- dev/com.ibm.ws.st.core_tests/resources/validation/includeConflictIgnore4/c.xml
- dev/com.ibm.ws.st.core_tests/resources/validation/includeConflictIgnore4/server.xml
Fixed the include conflict resolution for variables to work the same as the runtime.  The runtime has a master config and merges in each element as it sees it.  So even in the following case, the port will be 8001.
server.xml:
```
<server>
<featureManager>
<feature>servlet-4.0</feature>
<feature>localConnector-1.0</feature>
</featureManager>
<httpEndpoint httpPort="${port}" httpsPort="9443" id="defaultHttpEndpoint"/>
<applicationManager autoExpand="true"/>
<include location="includeA.xml" onConflict="IGNORE"/>
<applicationMonitor updateTrigger="mbean"/>
</server>
```
includeA.xml:
```
<server>
<variable name="port" value="8001" />
<variable name="port" value="8002" />
</server>
```
> Issue #282: Fix include conflict resolution for variables

- dev/com.ibm.ws.st.core_tests/resources/sampleTesting/JAXWSEJBSample/server/server.xml
- dev/com.ibm.ws.st.core_tests/resources/sampleTesting/JAXWSWebSample/server/server.xml
The JAXWS sample tests have the application already in the server.xml.  Remove it as the tools should be adding the application to the server as part of the test.
Also remove the duplicated copyright statements in server.xml.
> Issue #291: Remove applications from the server.xml for JAXWS sample tests

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/config/ConfigUtils.java
- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/config/DOMUtils.java
Fixes #293 
When working with a particular runtime, pass it along so that methods accessing all runtimes do not get invoked.
> Issue #293: Fix runtime deadlock resolving includes

- dev/com.ibm.ws.st.core_tests/resources/jee/JEEPublishJCA/ExampleRA/.settings/org.eclipse.wst.common.project.facet.core.xml
Fixes #325 
Updating the Java version to 1.8 accidentally updated the jst.connector facet in the JEEPublishJCA test case to 1.8.  Put it back to 1.7.
> Issue #325: The jst.connector facet should be set to 1.7

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/generation/ResolverFeatureAdapter.java
Checked with the runtime team and the best thing to do for this method is to throw an UnsupportedOperationException as it should never be used for feature resolution.  It is only used for installing bundles.
> Issue #339: Add the getActivationType method to the FeatureResourceAdapter class

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/ConsoleMonitorThread.java
- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/WebSphereRuntime.java
- Increased the timeout for the server status command
- Calling the WebSphereRuntime.getServerStatus method now which differentiates between timeout, started, stopped and unknown
- If the server status times out, don't terminate the launch, instead check the process associated with the launch, if it is still going then loop around and try the server status again (after the time delay)
- Added more logging
- Eclipse did some formatting of comments
> Issue #350: Try again if the server status times out

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/launch/LibertyRemoteUtilityExecutionDelegate.java
Add `WLP_DEBUG_REMOTE=y` to the environment when launching for remote debug.  Since it is an environment variable it will just be ignored by older servers that do not support it.
> Issue #358: Add WLP_DEBUG_REMOTE to env when launching for remote debug

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/WebSphereRuntime.java
Fixes #367 
Increase the timeout for renaming metadata files from less than 1s to 5s.
> Issue #367: Increase the timeout for renaming metadata files

- README.md
It's fairly common for people to find new tools and projects on Github directly but the README doesn't really explain anything about how these tools are used. This PR just adds a link to the page that shows some docs relevant to the tools to help them get started.
> The README should probably link to some tools docs

- dev/com.ibm.etools.maven.liberty.integration/META-INF/MANIFEST.MF
- dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/internal/LibertyMaven.java
- dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/manager/internal/MavenProjectInspector.java
- dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/servertype/internal/LibertyMavenJEEPublisher.java
- dev/com.ibm.ws.st.liberty.buildplugin.integration/META-INF/MANIFEST.MF
- dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/internal/ILibertyBuildPluginImpl.java
- dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/internal/IProjectInspector.java
- dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/manager/internal/AbstractLibertyManager.java
- dev/com.ibm.ws.st.liberty.tools.base/feature.xml
Fixes https://github.com/OpenLiberty/open-liberty-tools/issues/348
Uses the `liberty:install-apps` goal when dealing with a liberty-maven-plugin < 3.0, otherwise uses the `liberty:deploy` goal.
https://github.com/rajivnathan/guide-maven-intro/tree/liberty-maven-plugin
Project | liberty-maven-plugin version | mvn goal used by tools 
--- | --- | ---
archetypeGen/ServletSample | 2.0 | liberty:install-apps
finish | 3.2 | liberty:deploy
1. Import the project as an existing maven project
2. Use Run As -> Maven Install to trigger the full build
3. Once the build completes you may be prompted to have a server automatically created for you. Select Yes.
4. You should see a Liberty server created in the `Servers` view. Start it and verify the app is working correctly.
5. Make a change to the …
> Fix for breaking liberty-maven-plugin changes

- dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/internal/LibertyMaven.java
- dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/manager/internal/MavenProjectInspector.java
- dev/com.ibm.etools.maven.liberty.integration/src/com/ibm/etools/maven/liberty/integration/servertype/internal/LibertyMavenJEEPublisher.java
- dev/com.ibm.ws.st.liberty.buildplugin.integration/src/com/ibm/ws/st/liberty/buildplugin/integration/internal/IProjectInspector.java
- dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/internal/LibertyGradle.java
Build failure:
```
[ant:echo] Started compilation of com.ibm.ws.st.liberty.gradle
[ant:javac] Compile failed; see the compiler error output for details.
[ant:echo] /Users/rajiv/git/open-liberty-tools/dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/internal/LibertyGradle.java:49: error: LibertyGradle is not abstract and does not override abstract method updateSrcConfig(IProject,LibertyBuildPluginConfiguration,IProgressMonitor) in ILibertyBuildPluginImpl
[ant:echo] public class LibertyGradle implements ILibertyBuildPluginImpl {
[ant:echo]        ^
[ant:echo] /Users/rajiv/git/open-liberty-tools/dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/internal/LibertyGradle.java:206: error: method does not override or implement a method from a supertype
[ant:echo] …
```
> Fix liberty gradle plugin build problem

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/WebSphereRuntimeLocator.java
Check for null runtime location in the WebSphereRuntimeLocator getRuntimeFromDir method.
> Issue #388: Check for null runtime location

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/WebSphereRuntimeClasspathHelper.java
Fixes #390
Feature names can contain `-` (my-feature-1.0) so when extracting the version from a feature need to look for the last instance of `-` rather than the first.
> Issue #390: Get the last instance of - when getting the version of a feature

- dev/com.ibm.ws.st.core_tests/resources/validation/unavailableElement/server.xml
Remove the elements that give errors with older runtimes so that the test will pass with old and new runtimes.
> Issue #392: Make sure the unavailable element test works with older runtimes

- dev/com.ibm.ws.st.core/META-INF/MANIFEST.MF
In Eclipse 2020.09 the org.eclipse.jdt.debug bundle stopped exporting
the com.sun.jdi package which stops the tools resolving. This
fix stops importing the package and switching to a Require-Bundle so
the package can be imported both on Eclipse 2020.09, but also earlier
releases.
Fixes issue #407
> 407 - Support Eclipse 2020.09

- dev/gradle.properties
The Waterloo University mirror no longer contains Oxygen 3A, and there is no longer a reason to use a mirror in Canada. This should fix the OLT build issues. Investigating consuming this from our own site going forward.
> Update target platform in gradle.properties to reference Eclipse download site

- dev/gradle.properties
The Waterloo University mirror no longer contains Oxygen 3A, and there is no longer a reason to use a mirror in Canada. This should fix the OLT build issues. Investigating consuming this from our own site going forward.
This PR adds the direct download URL, we believe the previous value would have been redirected
> Update target platform in gradle.properties to directly reference Eclipse download

- dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/manager/internal/GradleProjectInspector.java
To override using the default gradle tooling api version for when eclipse ships a version not compatible with the latest Java.
> Add override to specify which gradle version the liberty tools use

- dev/com.ibm.ws.st.liberty.gradle/src/com/ibm/ws/st/liberty/gradle/internal/LibertyGradleConstants.java
Liberty gradle plugin has dropped the installApps task in favor of the deploy task so swap over to using that
> Update gradle task for liberty plugin

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/WebSphereRuntimeClasspathHelper.java
We process a list of known clashing feature prefixes, but this code will
hit an NPE if one of the hard-coded prefixes doesn't match any feature
installed in the runtime.
> Fix NPE in addConflictingFeatures

- dev/com.ibm.ws.st.core/src/com/ibm/ws/st/core/internal/WASPublishControllerDelegate.java
Bypass publish checking if eclipse autopublish is disabled. Currently, even if Eclipse has auto publish set to disabled it still asks Open Liberty Tools to check if publishing is required. To work around this we will now check if auto publish is disabled and bypass the check, as this process is fairly intensive in larger projects.
> Autopublish fix

- dev/com.ibm.etools.maven.liberty.integration/META-INF/MANIFEST.MF
Thank you for the update, on the surface I think your fix would work but would like to run our automation tests against it. So I'm pushing this into a test branch that I can build against to try it out
Remove version dependency to org.eclipse.m2e.maven.runtime to allow the plugin to install on Eclipse JEE v2022-06,v2022-09,v2022-12
> Remove version dependency to org.eclipse.m2e.maven.runtime
